### ISSUE TITLE
Tasks to be done once we go public

### ISSUE THREAD

**Issue by pagarcia** [splineops/splineops#10]
Going public on GitHub will allow us to a series of privileges, mainly free access to GitHub actions. I note here the tasks to be done:

1. Generate automatically Sphinx documentation through GitHub server, and host and publish it in on a GitHub branch (typically called gh-pages). The instructions for GitHub to compile and generate such documentation are typically stored as deploy-docs.yml inside .github/workflows, with a script like this:

```
name: Deploy Sphinx Documentation to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true  # Enable LFS

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.9'
          auto-update-conda: true
          auto-activate-base: false

      - name: Create Conda environment
        run: conda create --name splineops_env python=3.9

      - name: Install dependencies
        run: |
          conda run -n splineops_env conda install cupy cuda-version=12.3 numpy scipy black mypy pytest matplotlib pooch ffmpeg -c conda-forge
          conda run -n splineops_env pip install tox hatch
          conda run -n splineops_env pip install sphinx nbsphinx sphinx_design sphinx_togglebutton sphinx_codeautolink sphinx_copybutton jupyter_sphinx sphinx-rtd-theme pydata-sphinx-theme
          conda run -n splineops_env pip install -e .

      - name: Install Pandoc
        uses: pandoc/actions/setup@main

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs
          git lfs install

      - name: Build documentation
        run: conda run -n splineops_env sphinx-build -b html docs/ docs/build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
```
The GitHub deployment server should be automatically called when updating a particular branch of the repo (ie not only when updating main branch).

2. Add testing using tox via GitHub Actions. As GitHub Actions provides a virtual machine, we'll use it to pass the tox tests as well, by properly updating the script of point 1.

3. Generate Binder links for the Jupyter notebooks automatically generated by Sphinx-Gallery. Follow the info here to generate those links: https://sphinx-gallery.github.io/stable/configuration.html#generate-binder-links-for-gallery-notebooks-experimental
